project:
  type: website
  output-dir: docs

website:
  title: "Yongjin Lee"
  site-url: https://yongjin-l.github.io
  description: "Educator and researcher creating innovative PE curricula that integrate technology and social-emotional learning to help students thrive."  
  page-navigation: true
  back-to-top-navigation: false
  comments: 
    utterances: 
      repo: mroad24.github.io
      label: utterances
      theme: body-light
      issue-term: title
      
  navbar:
    left:
      - text: About
        aria-label: "About"
        href: about/index.qmd
      - text: Research
        aria-label: "Research"
        href: research/index.qmd
      - text: Teaching
        aria-label: "Teaching"
        href: teaching/index.qmd
      - text: AI in Education
        aria-label: "AI in Education"
        href: ai_in_edu/index.qmd
      - text: CV
        aria-label: "CV"
        href: cv.qmd
      ##-  text: Projects
        ##aria-label: "Projects"
        ##href: projects/index.qmd
        
        
  page-footer: 
    left: "" 
     
    center: >-
      &#169; 2025 Yongjin Lee &#8729; Made with [Quarto](https://quarto.org)    

    right: ""
   

format:
  html:
    theme:
      - cosmo
      - brand
      - assets/jin-theme.scss
    grid: 
      content-mode: full
    
    css: styles.css
    toc: true
    lightbox: true
    include-after-body: assets/footer.html
